export const googleClientId = "162271606164-fkm6rg92j2hfdc313hn9rioggqo54am9.apps.googleusercontent.com"

export const baseurl = "http://localhost:4040/api/"

export const keys ={
    webTeamDetails:'WebSiteTeamDetails', 
    unitTeamDetail:'UnitTeamDetail', 
    guideDetails:'GuideDetails', 
    testomonialDetails:'testoDetails', 
    blogCategory:'blogCategory', 
    blogCategoryPublic:'blogCategoryPublic',
    blog:'blogDetails', 
    websiteSettings:'webSettings', 
    slider:'slider', 
    contact:'contactMessage', 
    normalTrek:'normalTrek', 
    virtualTrek:'virtualTrek', 
    userProfile:'userProfile', 
    detstinationDetails:'destinationDetails', 
    guides:'getGuides', 
    home:'homeDetails', 
    twoBlogs:'twoBlgos', 
    websiteSettings:'websiteSettings', 
    guideListing:'guideListing', 
    unitGuideListing:'unitGuideListing',
    virtualTrekDetails:'virtualTrekDetails',
    normalTrekDetails:'normalTrekDetails', 
    aboutTeam:'aboutTeam', 
    getGuideById:'getGuideById', 
    getVirtualBooking:'getVirtualBooking',
    getNormalBooking:'getNormalBooking', 
    destinationWishlist:'destinationWishlist', 
    guideWishlist:'guideWishlist',
    getTestomonial:'getTestomonial', 
    checkForgetPassword:'checkForgetPassword', 
    blogInfinite:'blogInfinite', 
    getSingleBlog:'getSingleBlog',
    getNormalBooking:'getNormalBooking',
    getVirtualBooking:'getVirtualBooking',
    dashboardMainPage:'dashboardMainPage', 
    getMyLives:'getMyLives', 
    getLiveDetails:'getLiveDetails' ,
    publicLive:'publicLive'
}